import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const input = path.join(root, 'config', 'sources.json');
const output = path.join(root, 'worker', 'config.generated.js');

const config = JSON.parse(await fs.readFile(input, 'utf8'));
const generated = `// AUTO-GENERATED by scripts/generate_worker_config.mjs. Do not edit by hand.\n` +
  `export const SOURCE_CONFIG = ${JSON.stringify(config, null, 2)};\n` +
  `export const SOURCES = SOURCE_CONFIG.sources.map((source) => ({\n` +
  `  company: source.company,\n` +
  `  name: source.name,\n` +
  `  url: source.url,\n` +
  `  allow: source.allowed_path_prefixes || [],\n` +
  `}));\n` +
  `export const TOPICS = SOURCE_CONFIG.topic_keywords || {};\n`;

await fs.writeFile(output, generated, 'utf8');
console.log(`Generated ${path.relative(root, output)} from ${path.relative(root, input)}`);
